# Use a newer Node.js version
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire frontend folder
COPY . .

# Expose the frontend port
EXPOSE 5173

# Command to run the frontend server
CMD ["npm", "run", "dev"]
